### ISSUE TITLE
Project review #1

### ISSUE THREAD

**Issue by Chyrion** [Regularmute/MTGCardTracker#1]
### Pros:
- When no errors are thrown, the intended user experience is okay
- Lack of styling aside, the interface is fine to use and everything does what you expect it to do

### To improve:
- I accidentally deleted cards because the 'delete card' button blends in with the other functions, and I would expect the 'delete' option to be at the bottom instead of being the first button
- A shared layout could be nice across pages to have the same navigation options available everywhere (home/collections/logout); currently mildly confusing at times
- A clear page title for each page would make it easier to know where you are by glance

- As mentioned in the README, some errors popped up that were fixed by refreshing/returning. These included:
	- Registration failed on my first attempt, don't know why, and it threw a server error page instead of the error template
	- Collection was not available at first, returned and accessed it again -> worked
	- This failed again later without a clear reason (was not inactive)
	- After 1 minute of inactivity, attempting any of the following fails:
		- Add a card
		- Add/remove win/loss
		- Delete collection
- Probably caused by the CSRF token?

- Collection names accept just spaces, which makes them inaccessible

## Code:

The code is well structured, consistent and easy enough to follow. There is nothing overly complex that would warrant comments to explain in the code which is great. 

Database is used well, with the only thing even remotely worth noting about it is the extremely mild inconsistency in quotes used (in cards.py, some SQL commands are wrapped in triple quotes while others only have single quotes).
One not-bad-but-maybe-worth-improving thing is that SQL could maybe be used for slightly more complex uses, like calculating statistics directly with a query instead of doing them within the webpage - I don't know which is more efficient or easier to use for further features.

**Comment by Regularmute** [comment]
Thank you very much for your suggestions! I'll take your observations into account with future iterations. Also thank you for pointing out that the application currently accepts names consisting of only spaces; I hadn't thought of that possibility.

Have a nice day and good luck on your project as well!

**Comment by Regularmute** [comment]
Thank you very much for your suggestions! I'll take your observations into account with future iterations. Also thank you for pointing out that the application currently accepts names consisting of only spaces; I hadn't thought of that possibility.

Have a nice day and good luck on your project as well!

**Comment by Regularmute** [comment]
Closing this issue as of the latest deployment. New features include but are not limited to following fixes:

* The application has styling, improving legibility of the pages.
* A navigation bar has been added.
* Deleting cards now requires confirmation.
* Page titles have been improved and added.
* Internal server errors (500) should not occur. I believe the cause was the server shutting down when inactive. The application now sends "pre-pings" before queries to make sure the server is ready for them.
* Inputs parse spaces before submitting, and should not accept empty fields.
* SQL queries have been utilized in more ways, including but not limited to:
** tracking win rate in its own separate column with conditional queries to prevent division by zero
** various queries with INNER JOIN to utilize references between multiple tables

Thank you very much for your feedback. They have been very helpful with developing the application!
